@extends('site.layouts.master')
@section('content')
<div class="zr-page-hero"><div class="container"><span class="zr-eyebrow zr-eyebrow-light">UNIVERSITY SERVICES / خدمات الجامعة</span><h1>Institutes, Centers & Units / المعاهد والمراكز والوحدات</h1><p>Central directory for university institutes, research centers and administrative units.</p></div></div>
<div class="container" style="padding:45px 15px 70px"><div class="row">
<div class="col-md-4 col-sm-6" style="margin-bottom:25px"><a href="{{ url('services') }}" class="zr-college-card" style="display:block;background:#fff;border:1px solid #dceaf3;border-radius:18px;padding:28px;min-height:190px;box-shadow:0 10px 28px rgba(12,91,143,.08)"><i class="fa fa-cogs" style="font-size:34px;color:#0c5b8f"></i><h3 style="color:#082c4c;font-weight:800">University Services</h3><p>Administrative and digital services provided by the university.</p></a></div>
<div class="col-md-4 col-sm-6" style="margin-bottom:25px"><a href="{{ url('student-portal') }}" class="zr-college-card" style="display:block;background:#fff;border:1px solid #dceaf3;border-radius:18px;padding:28px;min-height:190px;box-shadow:0 10px 28px rgba(12,91,143,.08)"><i class="fa fa-graduation-cap" style="font-size:34px;color:#0c5b8f"></i><h3 style="color:#082c4c;font-weight:800">Student Services</h3><p>Registration, results, semesters and academic transcripts.</p></a></div>
<div class="col-md-4 col-sm-6" style="margin-bottom:25px"><a href="https://me.classera.com/" target="_blank" rel="noopener noreferrer" class="zr-college-card" style="display:block;background:#fff;border:1px solid #dceaf3;border-radius:18px;padding:28px;min-height:190px;box-shadow:0 10px 28px rgba(12,91,143,.08)"><i class="fa fa-laptop" style="font-size:34px;color:#0c5b8f"></i><h3 style="color:#082c4c;font-weight:800">E-Learning / Classera</h3><p>Direct access to the electronic learning platform.</p></a></div>
</div><div class="alert alert-info" style="border-radius:14px;margin-top:15px">This central directory is ready for publishing official institute, center and administrative-unit profiles.</div></div>
@endsection
