@extends('site.layouts.master')
@section('content')
<div class="zr-page-hero zr-portal-subhero"><div class="container"><span class="zr-eyebrow zr-eyebrow-light">@lang('site.getContent',['ar'=>'بوابة الطالب','en'=>'STUDENT PORTAL'])</span><h1>@lang('site.getContent',['ar'=>'تسجيل الطلاب','en'=>'Student Registration'])</h1><p>@lang('site.getContent',['ar'=>'أدخل بياناتك الأكاديمية وأرفق إشعار الدفع لإرسال طلب التسجيل.','en'=>'Enter your academic data and attach your payment receipt to submit the registration request.'])</p></div></div>
<div class="zr-portal-form-page"><div class="container"><div class="row"><div class="col-md-8 col-md-offset-2"><div class="zr-form-card">
<div class="zr-form-head"><i class="fa fa-graduation-cap"></i><div><h2>Student Registration Form / نموذج تسجيل الطالب</h2><p>All fields marked * are required / جميع الحقول بعلامة * إلزامية</p></div></div>
@if($errors->any())<div class="zr-alert zr-alert-danger"><strong>Please correct the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(session('success'))<div class="zr-alert zr-alert-success"><strong>{{ session('success') }}</strong></div>@endif
<form method="POST" action="{{ route('student.register.submit') }}" class="zr-form" enctype="multipart/form-data">@csrf
<div class="zr-form-section"><h3><i class="fa fa-id-card"></i> Basic Information / البيانات الأساسية</h3><div class="row">
<div class="col-md-6"><div class="form-group"><label>Student Number * / رقم الطالب *</label><input type="text" name="student_number" class="form-control" value="{{ old('student_number') }}" required placeholder="20231234"></div></div>
<div class="col-md-6"><div class="form-group"><label>National ID / الرقم الوطني</label><input type="text" name="national_id" class="form-control" value="{{ old('national_id') }}"></div></div>
<div class="col-md-6"><div class="form-group"><label>Name (Arabic) * / الاسم بالعربية *</label><input type="text" name="name_ar" class="form-control" value="{{ old('name_ar') }}" required></div></div>
<div class="col-md-6"><div class="form-group"><label>Name (English) / الاسم بالإنجليزية</label><input type="text" name="name_en" class="form-control" value="{{ old('name_en') }}"></div></div>
<div class="col-md-6"><div class="form-group"><label>Email / البريد الإلكتروني</label><input type="email" name="email" class="form-control" value="{{ old('email') }}" dir="ltr"></div></div>
<div class="col-md-6"><div class="form-group"><label>Phone / الهاتف</label><input type="text" name="phone" class="form-control" value="{{ old('phone') }}" dir="ltr"></div></div>
</div></div>
<div class="zr-form-section"><h3><i class="fa fa-university"></i> Academic Information / البيانات الأكاديمية</h3><div class="row">
<div class="col-md-6"><div class="form-group"><label>College * / الكلية *</label><select name="college_id" id="collegeSelect" class="form-control" required><option value="">— Select College —</option>@foreach($colleges as $college)<option value="{{ $college->id }}" @if(old('college_id')==$college->id) selected @endif>{{ $college->name_en ?: $college->name_ar }} / {{ $college->name_ar }}</option>@endforeach</select></div></div>
<div class="col-md-6"><div class="form-group"><label>Department / القسم</label><select name="department_id" id="departmentSelect" class="form-control"><option value="">— Select Department —</option>@foreach($departments as $dept)<option value="{{ $dept->id }}" data-college="{{ $dept->college_id }}" @if(old('department_id')==$dept->id) selected @endif>{{ $dept->titleEn ?: $dept->title }} / {{ $dept->title }}</option>@endforeach</select></div></div>
<div class="col-md-6"><div class="form-group"><label>Academic Year / العام الدراسي</label><select name="academic_year" class="form-control"><option value="">— Select Academic Year —</option>@for($y=date('Y');$y>=date('Y')-6;$y--)<option value="{{ $y }} - {{ $y+1 }}" @if(old('academic_year')==($y.' - '.($y+1))) selected @endif>{{ $y }} - {{ $y+1 }}</option>@endfor</select></div></div>
<div class="col-md-6"><div class="form-group"><label>Level / المستوى</label><select name="level" class="form-control"><option value="">— Select Level —</option>@foreach(['1'=>'Level 1 / المستوى الأول','2'=>'Level 2 / المستوى الثاني','3'=>'Level 3 / المستوى الثالث','4'=>'Level 4 / المستوى الرابع','5'=>'Level 5 / المستوى الخامس'] as $v=>$label)<option value="{{ $v }}" @if(old('level')==$v) selected @endif>{{ $label }}</option>@endforeach</select></div></div>
</div></div>
<div class="zr-form-section" style="background:#f7fbff;border:1px solid #d9eaf7;padding:20px;border-radius:10px"><h3><i class="fa fa-file-upload"></i> Payment Receipt / إشعار الدفع</h3><p>Upload a clear JPG, PNG or PDF receipt. Maximum 2 MB. / ارفع صورة واضحة أو ملف PDF لإشعار الدفع، بحد أقصى 2 ميجابايت.</p><div class="form-group"><label>Payment Receipt * / إشعار الدفع *</label><input type="file" name="payment_receipt" class="form-control" accept=".jpg,.jpeg,.png,.pdf" required><small>Allowed: JPG, JPEG, PNG, PDF — Max: 2MB</small></div></div>
<div class="zr-form-actions"><button type="submit" class="zr-btn zr-btn-primary zr-btn-lg"><i class="fa fa-paper-plane"></i> Register Student / تسجيل الطالب</button><a href="{{ route('student.portal') }}" class="zr-btn zr-btn-ghost"><i class="fa fa-arrow-left"></i> Back to Portal</a></div>
</form></div></div></div></div>
</div>
@endsection
@section('scripts')<script>$(function(){var c=$('#collegeSelect'),d=$('#departmentSelect');function f(){var id=c.val();d.find('option').each(function(){var x=$(this).data('college');$(this).toggle(!x||!id||x==id);});}c.on('change',f);f();});</script>@endsection
