@extends('site.layouts.master')
@section('content')
<div class="container" style="padding:35px 15px">
    <h2>Academic Management / الإدارة الأكاديمية</h2>
    <p class="text-muted">Create academic years, semesters and courses, then enroll students and publish grades.</p>

    @if(session('success')) <div class="alert alert-success">{{ session('success') }}</div> @endif
    @if($errors->any()) <div class="alert alert-danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif

    <div class="row">
        <div class="col-md-6"><div class="panel panel-default"><div class="panel-heading"><strong>Academic Year</strong></div><div class="panel-body"><form method="POST" action="{{ route('academic-management.academic-year.store') }}">@csrf<div class="form-group"><label>Name</label><input class="form-control" name="name" placeholder="2026 - 2027" required></div><div class="form-group"><label>Arabic Name</label><input class="form-control" name="name_ar"></div><div class="row"><div class="col-sm-6"><input class="form-control" type="date" name="start_date"></div><div class="col-sm-6"><input class="form-control" type="date" name="end_date"></div></div><div class="checkbox"><label><input type="checkbox" name="is_current" value="1"> Current year</label></div><button class="btn btn-primary">Create Academic Year</button></form></div></div></div>
        <div class="col-md-6"><div class="panel panel-default"><div class="panel-heading"><strong>Semester</strong></div><div class="panel-body"><form method="POST" action="{{ route('academic-management.semester.store') }}">@csrf<div class="form-group"><label>Academic Year</label><select class="form-control" name="academic_year_id" required>@foreach($academicYears as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</select></div><div class="row"><div class="col-sm-8"><input class="form-control" name="name" placeholder="First Semester" required></div><div class="col-sm-4"><input class="form-control" type="number" name="semester_number" min="1" max="3" value="1" required></div></div><br><input class="form-control" name="name_ar" placeholder="اسم الفصل بالعربية"><br><button class="btn btn-primary">Create Semester</button></form></div></div></div>
    </div>

    <div class="panel panel-default"><div class="panel-heading"><strong>Course</strong></div><div class="panel-body"><form class="row" method="POST" action="{{ route('academic-management.course.store') }}">@csrf<div class="col-md-2"><input class="form-control" name="code" placeholder="CS101" required></div><div class="col-md-3"><input class="form-control" name="name" placeholder="Course name" required></div><div class="col-md-3"><input class="form-control" name="name_ar" placeholder="اسم المقرر"></div><div class="col-md-2"><select class="form-control" name="department_id"><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->titleEn ?: $department->title }}</option>@endforeach</select></div><div class="col-md-1"><input class="form-control" type="number" name="credit_hours" value="3" min="1" max="20" required></div><div class="col-md-1"><button class="btn btn-success">Add</button></div></form></div></div>

    <div class="row">
        <div class="col-md-6"><div class="panel panel-default"><div class="panel-heading"><strong>Enroll Student</strong></div><div class="panel-body"><form method="POST" action="{{ route('academic-management.enrollment.store') }}">@csrf<select class="form-control" name="student_id" required><option value="">Student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->student_number }} — {{ $student->name_en ?: $student->name_ar }}</option>@endforeach</select><br><select class="form-control" name="course_id" required><option value="">Course</option>@foreach($courses as $course)<option value="{{ $course->id }}">{{ $course->code }} — {{ $course->name }}</option>@endforeach</select><br><select class="form-control" name="semester_id" required><option value="">Semester</option>@foreach($academicYears as $year)@foreach($year->semesters as $semester)<option value="{{ $semester->id }}">{{ $year->name }} — {{ $semester->name }}</option>@endforeach @endforeach</select><br><input type="hidden" name="status" value="enrolled"><button class="btn btn-primary">Enroll</button></form></div></div></div>
        <div class="col-md-6"><div class="panel panel-default"><div class="panel-heading"><strong>Publish Grade</strong></div><div class="panel-body"><form method="POST" action="{{ route('academic-management.grade.store') }}">@csrf<select class="form-control" name="student_id" required><option value="">Student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->student_number }} — {{ $student->name_en ?: $student->name_ar }}</option>@endforeach</select><br><select class="form-control" name="course_id" required><option value="">Course</option>@foreach($courses as $course)<option value="{{ $course->id }}">{{ $course->code }} — {{ $course->name }}</option>@endforeach</select><br><select class="form-control" name="semester_id" required><option value="">Semester</option>@foreach($academicYears as $year)@foreach($year->semesters as $semester)<option value="{{ $semester->id }}">{{ $year->name }} — {{ $semester->name }}</option>@endforeach @endforeach</select><br><div class="row"><div class="col-sm-4"><input class="form-control" name="midterm" type="number" step="0.01" placeholder="Midterm"></div><div class="col-sm-4"><input class="form-control" name="final" type="number" step="0.01" placeholder="Final"></div><div class="col-sm-4"><input class="form-control" name="practical" type="number" step="0.01" placeholder="Practical"></div></div><br><div class="row"><div class="col-sm-4"><input class="form-control" name="total_score" type="number" step="0.01" placeholder="Total"></div><div class="col-sm-4"><input class="form-control" name="letter_grade" placeholder="A+"></div><div class="col-sm-4"><input class="form-control" name="grade_points" type="number" step="0.01" min="0" max="4" placeholder="Points"></div></div><br><button class="btn btn-success">Save Grade</button></form></div></div></div>
    </div>
</div>
@endsection
